stages:
  generate_review_activity_dataset:
    cmd: python main.py -m dataset
    deps:
    - data/base/consolidated_profiles.csv
    - pipeline/generator.py
    - preprocess/preprocessor.py
    - utils/clean.py
    - utils/extract.py
    - utils/reformat.py
    outs:
    - data/uc2/interim/consolidated_review_activity.csv
  feature_engineering:
    cmd: python main.py -m build_features
    deps:
    - data/base/consolidated_profiles.csv
    - data/base/consolidated_products.csv
    - data/base/consolidated_product_info.csv
    - data/uc2/interim/consolidated_review_activity.csv
    - src/features/build_features.py
    - engineer/engineer.py
    - pipeline/engineer.py
    - utils/clean.py
    - utils/engineer.py
    - utils/engineer_functions.py
    outs:
    - data/uc2/processed/fake_framework_features.csv
