stages:
  generate_review_activity_dataset:
    cmd: python main.py -m dataset
    deps:
    - data/base/consolidated_profiles.csv
    - pipeline/generator.py
    - preprocess/preprocessor.py
    - utils/clean.py
    - utils/extract.py
    - utils/reformat.py
    outs:
    - data/uc2/interim/consolidated_review_activity.csv
    - models/word_embedding/doc2vec.model
    - data/uc2/interim/doc2vec_embedding.csv
  feature_engineering:
    cmd: python main.py -m build_features
    deps:
    - data/base/consolidated_profiles.csv
    - data/uc2/interim/consolidated_products_labelled.csv
    - data/base/consolidated_product_info.csv
    - data/uc2/interim/consolidated_review_activity.csv
    - src/features/build_features.py
    - engineer/engineer.py
    - pipeline/engineer.py
    - utils/clean.py
    - utils/engineer.py
    - utils/engineer_functions.py
    - models/word_embedding/doc2vec.model
    - data/uc2/interim/doc2vec_embedding.csv
    outs:
    - data/uc2/processed/fake_framework_features.csv
    - data/uc2/interim/consolidated_profiles.csv
    - models/normalizer/cosine_similarity_tfidf.pkl
  train_model:
    cmd: python main.py -m train_model -model ocsvm -feature_select n -normalize y -text_represent doc2vec
    deps:
    - data/uc2/processed/fake_framework_features.csv
    - data/uc2/interim/doc2vec_embedding.csv
    - src/models/train_model.py
    - impactscorer/impactscorer.py
    - pipeline/trainer.py
    - featureselector/featureselector.py
    - trainers/models.py
    outs:
    - data/uc2/processed/suspicious_reviewers_metrics.csv
    - models/normalizer/feature_normalizer_standard.pkl
    - models/results/ocsvm_results.csv
    - models/ocsvm.pkl
